/**
 * Task history, generated by running the real demo engine on a virtual clock: every seeded task has
 * a genuine event timeline, steps, verifications, approvals, logs, audit entries and notifications —
 * exactly what a live run produces. Human decisions (approve / reject / answer / resume / cancel)
 * are injected at the moments the engine waits for them.
 */
import type { VirtualScheduler } from "../server/clock";
import type { DemoEngine } from "../server/engine";
import { DEMO_GOALS } from "../server/scenarios";
import type { DemoStore, TaskRec } from "../server/store";
import { DAY, HOUR, iso, MINUTE, random, seedId } from "../server/util";
import { AGENT_IDS } from "./agents";
import { AUTOMATION_IDS } from "./automations";
import { TEAMMATE_ID } from "./workspace";

type Human = "approve" | "reject" | "cancel" | { answer: string } | "resume";

interface Seed {
  goal: string;
  ago: number;
  agentId?: string;
  script?: Human[];
  userId?: string;
  automation?: string;
}

function drive(store: DemoStore, engine: DemoEngine, vs: VirtualScheduler, seed: Seed, now: number): TaskRec {
  vs.setTime(now - seed.ago);
  let runId: string | null = null;
  if (seed.automation) {
    runId = seedId(0x42, Math.round(seed.ago / MINUTE));
    store.automationRuns.push({
      id: runId,
      automation_id: seed.automation,
      scheduled_for: iso(vs.now()),
      trigger: "schedule",
      status: "created",
      attempts: 1,
      error: null,
      next_attempt_at: null,
      task_id: null,
      created_at: iso(vs.now()),
      finished_at: null,
    });
  }
  const task = engine.createTask(
    { goal: seed.goal, agentId: seed.agentId ?? null, context: null, priority: 100 },
    { source: seed.automation ? "automation" : "api", automationRunId: runId, userId: seed.userId },
  );
  if (runId) {
    const run = store.automationRuns.find((r) => r.id === runId)!;
    run.task_id = task.id;
  }
  const script = [...(seed.script ?? [])];
  for (let guard = 0; guard < 20; guard++) {
    vs.runUntilIdle();
    const next = script[0];
    if (next === undefined) break;
    const pending = [...store.approvals.values()].find((a) => a.task_id === task.id && a.status === "pending");
    vs.advance(Math.round((1.5 + random() * 5) * MINUTE)); // a human takes a few minutes
    if (next === "cancel") engine.cancel(task);
    else if (next === "resume" && task.status === "failed") engine.resume(task);
    else if (typeof next === "object" && task.status === "waiting_input") engine.provideInput(task, next.answer);
    else if (next === "approve" && pending) engine.approve(pending, null);
    else if (next === "reject" && pending) engine.reject(pending, "Not now — I'll send this myself after the review.");
    else break;
    script.shift();
  }
  vs.runUntilIdle();
  return task;
}

export function seedHistory(store: DemoStore, engine: DemoEngine, vs: VirtualScheduler, now: number): void {
  const seeds: Seed[] = [
    {
      goal: "Schedule a 30-minute meeting with Sara tomorrow after 2 PM and send her a confirmation email.",
      ago: 6 * DAY + 3 * HOUR,
      agentId: AGENT_IDS.assistant,
      script: ["approve", "approve"],
    },
    { goal: "Summarize my unread e-mails from the last 24 hours.", ago: 5 * DAY + 5 * HOUR, userId: TEAMMATE_ID },
    { goal: "Draft a follow-up email to Omar about the Q3 roadmap.", ago: 4 * DAY + 2 * HOUR },
    {
      goal: "Schedule a sync with Priya tomorrow after 2 PM — the calendar API has been flaky all day.",
      ago: 3 * DAY + 6 * HOUR,
    },
    { goal: "Remember that Rahim prefers video calls over phone calls.", ago: 2 * DAY + 4 * HOUR },
    {
      goal: "Summarize my unread e-mails from the last 24 hours.",
      ago: 2 * DAY - 7 * HOUR,
      automation: AUTOMATION_IDS.digest,
      agentId: AGENT_IDS.triage,
    },
    { goal: DEMO_GOALS.answer, ago: DAY + 8 * HOUR },
    { goal: "Send an email to Omar with the updated launch date.", ago: DAY + 2 * HOUR, script: ["reject"] },
    {
      goal: "Summarize my unread e-mails from the last 24 hours.",
      ago: DAY - 7 * HOUR,
      automation: AUTOMATION_IDS.digest,
      agentId: AGENT_IDS.triage,
    },
    {
      goal: "Schedule a meeting with Rahim next week to review the partnership draft.",
      ago: 5 * HOUR,
      script: ["cancel"],
    },
    { goal: "Send an email to Priya with a short status update on the proposal.", ago: 42 * MINUTE },
    { goal: "Schedule a meeting with Zoe tomorrow afternoon and send her a confirmation.", ago: 16 * MINUTE },
  ];
  for (const seed of seeds.sort((a, b) => b.ago - a.ago)) drive(store, engine, vs, seed, now);

  // What still needs the user stays unread; everything else older than a few minutes has been seen.
  for (const n of store.notifications) {
    if (n.read_at || n.idemKey.startsWith("seed:")) continue; // static fixtures set their own state
    const task = store.tasks.get(String(n.data.task_id ?? ""));
    const approval = store.approvals.get(String(n.data.approval_id ?? ""));
    const open =
      (n.event_type === "approval_required" && approval?.status === "pending") ||
      (n.event_type === "input_required" && task?.status === "waiting_input") ||
      (n.event_type === "task_failed" && task?.status === "failed" && task.failureCode !== "approval_rejected");
    const t = Date.parse(n.created_at);
    if (!open && now - t > 10 * MINUTE) n.read_at = iso(Math.min(now, t + 25 * MINUTE));
  }
}
