import type { Metadata } from "next";

export const SITE_NAME = "AgentOS";
export const SITE_TAGLINE = "Give AI a goal. AgentOS gets the work done.";
export const SITE_DESCRIPTION =
  "AgentOS is an operating system for AI agents that act: it plans, executes, verifies and recovers real work across Gmail, Calendar, Drive, the web and your tools — with policy, approvals and a full audit trail.";

/** The social card generated by `src/app/opengraph-image.tsx` / `twitter-image.tsx`. */
const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "AgentOS — Give AI a goal. AgentOS gets the work done.",
};
const TWITTER_IMAGE = { ...OG_IMAGE, url: "/twitter-image" };

/**
 * Per-page metadata for public pages: title, description, canonical URL, Open Graph and Twitter.
 * A page-level `openGraph` replaces the parent's (including file-based images), so the generated
 * social images are referenced explicitly.
 */
export function marketingMetadata({
  title,
  description,
  path,
  home = false,
}: {
  title: string;
  description: string;
  path: string;
  home?: boolean;
}): Metadata {
  const fullTitle = home ? title : `${title} · ${SITE_NAME}`;
  return {
    title: home ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    robots: { index: true, follow: true },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_US",
      title: fullTitle,
      description,
      url: path,
      images: [OG_IMAGE],
    },
    twitter: { card: "summary_large_image", title: fullTitle, description, images: [TWITTER_IMAGE] },
  };
}
