"""User-facing execution summary, built deterministically from durable state.

It reports what happened, what changed (with external references), what was
verified and how, what failed, and what is waiting for the user. It is never
generated by a model and never contains hidden reasoning.
"""

from __future__ import annotations

from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.approvals.models import ApprovalRequest
from app.tasks import repository as task_repo
from app.tasks.models import Task
from app.verification.models import VerificationResult

_STATUS_HEADLINES = {
    "completed": "Done — every action was verified.",
    "failed": "The task did not complete.",
    "cancelled": "The task was cancelled.",
    "waiting_approval": "Waiting for your approval.",
    "waiting_input": "Waiting for your input.",
    "blocked": "Blocked — action needed from you.",
    "requires_reconciliation": "Needs your confirmation before continuing.",
    "expired": "Expired while waiting.",
}


async def build_summary(session: AsyncSession, task: Task) -> dict[str, Any]:
    steps = await task_repo.current_steps(session, task)
    verifications = (await session.execute(
        select(VerificationResult).where(VerificationResult.task_id == task.id, VerificationResult.scope == "step")
        .order_by(VerificationResult.verified_at))).scalars().all()
    latest_verification = {v.step_id: v for v in verifications}
    pending_approvals = (await session.execute(
        select(ApprovalRequest).where(ApprovalRequest.task_id == task.id, ApprovalRequest.status == "pending")
    )).scalars().all()

    happened, changed, verified, failed = [], [], [], []
    for st in steps:
        happened.append({"step": st.step_key, "action": st.action, "tool": st.tool_name, "status": st.status,
                         "summary": st.output_summary})
        if st.status == "completed" and st.permission_level != "read":
            changed.append({"step": st.step_key, "tool": st.tool_name, "description": st.output_summary,
                            "external_ref": st.external_ref})
        v = latest_verification.get(st.id)
        if v is not None:
            verified.append({"step": st.step_key, "method": v.method, "status": v.status,
                             "differences": [d.get("field") for d in (v.differences or [])][:5]})
        if st.status in ("failed", "blocked", "requires_reconciliation"):
            failed.append({"step": st.step_key, "tool": st.tool_name, "status": st.status,
                           "error_class": st.error_class, "message": st.error_message})
    waiting: list[dict[str, Any]] = [{"type": "approval", "approval_id": str(a.id), "summary": a.summary,
                                      "expires_at": a.expires_at.isoformat()} for a in pending_approvals]
    for question in task.pending_questions or []:
        waiting.append({"type": "input", "question": question})
    if task.status == "requires_reconciliation":
        waiting.extend({"type": "confirm_outcome", "step": f["step"], "message": f["message"]}
                       for f in failed if f["status"] == "requires_reconciliation")
    headline = _STATUS_HEADLINES.get(task.status, f"Task is {task.status.replace('_', ' ')}.")
    if task.status == "failed" and task.failure_message:
        headline = f"The task did not complete: {task.failure_message[:300]}"
    if changed and task.status == "completed":
        headline = "Done: " + "; ".join((c["description"] or c["tool"]) for c in changed)[:600]
    summary: dict[str, Any] = {
        "status": task.status,
        "headline": headline,
        "what_happened": happened,
        "what_changed": changed,
        "what_was_verified": verified,
        "what_failed": failed,
        "waiting_for_user": waiting,
        "partial_completion": bool(changed) and task.status != "completed",
    }
    direct = (task.plan or {}).get("direct_response")
    if direct:
        summary["direct_response"] = direct
        summary["direct_response_note"] = "Answered by the model without taking any action; not externally verified."
    return summary
