/** Task/step state machines, ported from `backend/app/tasks/state.py`. Only these transitions are legal. */
import type { StepStatus, TaskStatus } from "@/lib/api";

export const TASK_TRANSITIONS: Record<TaskStatus, readonly TaskStatus[]> = {
  created: ["planning", "cancelled", "failed", "cancel_requested"],
  planning: ["planned", "waiting_input", "failed", "blocked", "cancel_requested", "cancelled"],
  planned: ["validating", "cancelled", "cancel_requested", "failed"],
  validating: ["queued", "planning", "blocked", "failed", "cancelled", "cancel_requested", "waiting_input"],
  queued: ["running", "cancelled", "paused", "failed", "expired", "cancel_requested"],
  running: [
    "verifying",
    "waiting_approval",
    "waiting_input",
    "recovering",
    "requires_reconciliation",
    "queued",
    "failed",
    "blocked",
    "cancel_requested",
    "paused",
    "planning",
    "cancelled",
  ],
  verifying: ["completed", "failed", "recovering", "running", "requires_reconciliation", "cancel_requested", "queued"],
  recovering: [
    "queued",
    "running",
    "planning",
    "waiting_input",
    "waiting_approval",
    "blocked",
    "failed",
    "requires_reconciliation",
    "cancel_requested",
  ],
  waiting_approval: ["queued", "failed", "cancelled", "expired", "paused", "running"],
  waiting_input: ["planning", "queued", "cancelled", "expired", "failed"],
  requires_reconciliation: ["queued", "running", "failed", "cancelled", "waiting_input"],
  paused: ["queued", "cancelled"],
  cancel_requested: ["cancelled", "failed", "completed", "requires_reconciliation"],
  blocked: ["queued", "planning", "cancelled", "failed"],
  failed: ["queued", "planning", "cancelled"],
  expired: ["queued", "cancelled"],
  completed: [],
  cancelled: [],
};

export const STEP_TRANSITIONS: Record<StepStatus, readonly StepStatus[]> = {
  pending: ["running", "waiting_approval", "waiting_input", "skipped", "cancelled", "blocked", "failed"],
  waiting_approval: ["running", "failed", "cancelled", "pending", "skipped"],
  waiting_input: ["pending", "cancelled", "failed", "skipped"],
  running: [
    "verifying",
    "waiting_external",
    "retry_scheduled",
    "requires_reconciliation",
    "failed",
    "blocked",
    "waiting_input",
    "cancelled",
    "pending",
    "completed",
  ],
  waiting_external: ["verifying", "failed", "retry_scheduled", "requires_reconciliation", "cancelled", "running"],
  verifying: ["completed", "failed", "retry_scheduled", "requires_reconciliation", "running"],
  retry_scheduled: ["running", "pending", "failed", "cancelled", "requires_reconciliation", "waiting_approval"],
  requires_reconciliation: ["verifying", "running", "pending", "failed", "completed", "cancelled", "waiting_input"],
  blocked: ["pending", "failed", "cancelled", "skipped"],
  failed: ["pending"],
  completed: [],
  skipped: ["pending"],
  cancelled: [],
};

export const STEP_TERMINAL = new Set<StepStatus>(["completed", "failed", "skipped", "cancelled"]);
export const TASK_ACTIVE = new Set<TaskStatus>([
  "created",
  "planning",
  "planned",
  "validating",
  "queued",
  "running",
  "verifying",
  "recovering",
  "cancel_requested",
  "waiting_approval",
  "waiting_input",
]);
