"""Memory ORM models.

* ``MemoryItem`` — one remembered fact/preference/contact, owned by exactly one user in one
  tenant. Carries provenance (``source_type``/``source_reference``), scoring signals
  (``confidence``/``importance``), freshness (``last_verified_at``/``expires_at``) and
  conflict state (``status``/``superseded_by``). A generated ``search_vector`` column backs
  keyword retrieval.
* ``MemoryEmbedding`` — the derived vector for a memory (pgvector, cosine/HNSW). Derived
  data: it is deleted together with the memory's sources as soon as the memory is deleted.
* ``MemorySource`` — source attribution rows (which task/tool/user statement produced or
  corroborated a memory), with a short sanitized excerpt.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import CheckConstraint, Computed, Float, ForeignKey, Index, Integer, String, Text, func, text
from sqlalchemy.dialects.postgresql import TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from app.common.enums import StrEnum
from app.common.time import utcnow
from app.core.database import Base, TenantScopedMixin, TimestampMixin, UUIDPrimaryKeyMixin

# Dimension of stored embeddings. Must match ``Settings.embedding_dimensions`` (checked by the embed job).
EMBEDDING_DIM = 768


class MemoryType(StrEnum):
    CONVERSATIONAL = "conversational"
    SHORT_TERM = "short_term"
    LONG_TERM = "long_term"
    SEMANTIC = "semantic"
    PREFERENCE = "preference"
    TASK_HISTORY = "task_history"
    VERIFIED_FACT = "verified_fact"
    CONTACT = "contact"


class MemoryStatus(StrEnum):
    ACTIVE = "active"
    SUPERSEDED = "superseded"  # replaced by a newer/more trusted value for the same subject
    CONFLICTED = "conflicted"  # contradicts an active memory but was not trusted enough to replace it
    DELETED = "deleted"  # soft-deleted; derived data already removed, row purged after retention


class MemorySourceType(StrEnum):
    USER_STATED = "user_stated"
    TASK = "task"
    TOOL_RESULT = "tool_result"
    EXTRACTION = "extraction"
    IMPORT = "import"


class MemoryItem(UUIDPrimaryKeyMixin, TenantScopedMixin, TimestampMixin, Base):
    __tablename__ = "memory_items"

    user_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False,
                                               index=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    memory_type: Mapped[str] = mapped_column(String(32), nullable=False)
    # Normalized key for conflict detection, e.g. ``contact:rahim:email`` or ``pref:meeting_length``.
    subject_key: Mapped[str | None] = mapped_column(String(200), nullable=True)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    importance: Mapped[float] = mapped_column(Float, nullable=False)
    source_type: Mapped[str] = mapped_column(String(20), nullable=False)
    source_reference: Mapped[str] = mapped_column(String(300), nullable=False)
    # sha256 over the normalized content; exact-duplicate detection among active memories.
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    status: Mapped[str] = mapped_column(String(16), nullable=False, default=MemoryStatus.ACTIVE.value,
                                        server_default=text("'active'"))
    superseded_by: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("memory_items.id", ondelete="SET NULL"), nullable=True)
    last_verified_at: Mapped[datetime] = mapped_column(nullable=False, default=utcnow,
                                                       server_default=func.now())
    expires_at: Mapped[datetime | None] = mapped_column(nullable=True)
    last_accessed_at: Mapped[datetime | None] = mapped_column(nullable=True)
    access_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default=text("0"))
    deleted_at: Mapped[datetime | None] = mapped_column(nullable=True)
    # Keyword retrieval: generated by PostgreSQL, never written by the application.
    search_vector: Mapped[Any] = mapped_column(
        TSVECTOR, Computed("to_tsvector('english', coalesce(content,''))", persisted=True),
        nullable=True, deferred=True)

    __table_args__ = (
        CheckConstraint("confidence >= 0 AND confidence <= 1", name="confidence_range"),
        CheckConstraint("importance >= 0 AND importance <= 1", name="importance_range"),
        CheckConstraint("status IN ('active','superseded','conflicted','deleted')", name="status_valid"),
        Index("ix_memory_items_tenant_user_status_type", "tenant_id", "user_id", "status", "memory_type"),
        Index("ix_memory_items_subject_key", "tenant_id", "user_id", "subject_key",
              postgresql_where=text("subject_key IS NOT NULL")),
        Index("uq_memory_items_active_content_hash", "tenant_id", "user_id", "content_hash", unique=True,
              postgresql_where=text("status = 'active'")),
        Index("ix_memory_items_source_reference", "tenant_id", "source_reference"),
        Index("ix_memory_items_deleted_at", "deleted_at", postgresql_where=text("deleted_at IS NOT NULL")),
        Index("ix_memory_items_search_vector", "search_vector", postgresql_using="gin"),
    )


class MemoryEmbedding(TenantScopedMixin, Base):
    """Derived vector for one memory. Replaceable by a dedicated vector store through
    ``app.memory.service.VectorIndex`` without touching the rest of the module."""

    __tablename__ = "memory_embeddings"

    memory_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("memory_items.id", ondelete="CASCADE"),
                                                 primary_key=True)
    model: Mapped[str] = mapped_column(String(100), nullable=False)
    dimensions: Mapped[int] = mapped_column(Integer, nullable=False)
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM), nullable=False)
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())

    __table_args__ = (
        Index("ix_memory_embeddings_embedding_hnsw", "embedding", postgresql_using="hnsw",
              postgresql_ops={"embedding": "vector_cosine_ops"}),
    )


class MemorySource(UUIDPrimaryKeyMixin, TenantScopedMixin, Base):
    """Source attribution: which user statement / task / tool result produced or corroborated a memory."""

    __tablename__ = "memory_sources"

    memory_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("memory_items.id", ondelete="CASCADE"),
                                                 nullable=False, index=True)
    source_type: Mapped[str] = mapped_column(String(20), nullable=False)
    source_id: Mapped[str] = mapped_column(String(300), nullable=False)
    excerpt: Mapped[str | None] = mapped_column(Text, nullable=True)  # sanitized, <= 500 chars
    created_at: Mapped[datetime] = mapped_column(nullable=False, server_default=func.now())

    __table_args__ = (Index("ix_memory_sources_source", "tenant_id", "source_type", "source_id"),)
