/**
 * Usage metering presentation (pure, unit-tested).
 *
 * Metric keys are the backend's `UsageKind` values (app/usage/models.py). Quotas come from the plan
 * (`UsageSummary.quotas`); a metric without a quota is not capped (the backend's `enforce_quota`
 * skips it). Quotas are enforced per organization per calendar month (UTC).
 */
import { bytes, compactNumber, durationMs, number } from "@/lib/format";
import type { Tone } from "@/lib/status";

export interface MetricMeta {
  label: string;
  description: string;
  unit: "count" | "seconds" | "bytes" | "tokens";
}

export const METRICS: Record<string, MetricMeta> = {
  task_created: { label: "Tasks", description: "Goals submitted to AgentOS", unit: "count" },
  model_call: {
    label: "Model calls",
    description: "Planner, reasoning and verification calls to AI models",
    unit: "count",
  },
  tool_call: {
    label: "Tool calls",
    description: "External actions such as reading a calendar or sending an e-mail",
    unit: "count",
  },
  browser_seconds: { label: "Browser time", description: "Time spent by the isolated browser agent", unit: "seconds" },
  search_query: { label: "Search queries", description: "Web searches run by agents or from Search", unit: "count" },
  automation_run: {
    label: "Automation runs",
    description: "Scheduled and triggered automation executions",
    unit: "count",
  },
  model_input_tokens: { label: "Model input tokens", description: "Tokens sent to AI models", unit: "tokens" },
  model_output_tokens: { label: "Model output tokens", description: "Tokens generated by AI models", unit: "tokens" },
  browser_action: {
    label: "Browser actions",
    description: "Clicks, typing and navigation by the browser agent",
    unit: "count",
  },
  storage_bytes: { label: "Storage", description: "Files stored", unit: "bytes" },
  embedding: { label: "Embeddings", description: "Vectors computed for memory and document search", unit: "count" },
};

/** Display order for quota meters (known metrics first, then any other quota keys). */
export const QUOTA_ORDER = [
  "task_created",
  "model_call",
  "tool_call",
  "browser_seconds",
  "search_query",
  "automation_run",
];

export function metricMeta(key: string): MetricMeta {
  return (
    METRICS[key] ?? {
      label: key.replace(/[_.-]+/g, " ").replace(/^\w/, (c) => c.toUpperCase()),
      description: "Metered usage",
      unit: "count",
    }
  );
}

export function formatMetric(key: string, value: number | null | undefined, opts: { compact?: boolean } = {}): string {
  if (value === null || value === undefined || !Number.isFinite(value)) return "—";
  const meta = metricMeta(key);
  if (meta.unit === "seconds") {
    if (value === 0) return "0 min";
    if (value >= 3600) {
      const hours = value / 3600;
      return `${hours >= 100 ? Math.round(hours).toLocaleString("en-US") : Number(hours.toFixed(1)).toString()} h`;
    }
    if (value >= 60) return `${Number((value / 60).toFixed(value < 600 ? 1 : 0)).toString()} min`;
    return durationMs(value * 1000);
  }
  if (meta.unit === "bytes") return bytes(value);
  const rounded = Number.isInteger(value) ? value : Math.round(value * 100) / 100;
  return opts.compact || meta.unit === "tokens" ? compactNumber(rounded) : number(rounded);
}

export interface Meter {
  key: string;
  used: number;
  limit: number | null;
  /** 0–100 (clamped) for the bar; null when unlimited. */
  percent: number | null;
  /** Unclamped ratio used/limit (can exceed 1). */
  ratio: number | null;
  remaining: number | null;
  state: "ok" | "near" | "at_limit" | "over" | "unlimited";
  tone: Tone;
}

export const NEAR_LIMIT = 0.8;

export function meterFor(key: string, used: number | undefined, limit: number | undefined | null): Meter {
  const u = Math.max(0, Number.isFinite(used) ? (used as number) : 0);
  if (limit === undefined || limit === null || !Number.isFinite(limit)) {
    return {
      key,
      used: u,
      limit: null,
      percent: null,
      ratio: null,
      remaining: null,
      state: "unlimited",
      tone: "neutral",
    };
  }
  if (limit <= 0) {
    // A zero quota means the metric is not included in the plan at all.
    return {
      key,
      used: u,
      limit,
      percent: 100,
      ratio: u > 0 ? Infinity : 1,
      remaining: 0,
      state: u > 0 ? "over" : "at_limit",
      tone: "danger",
    };
  }
  const ratio = u / limit;
  const percent = Math.min(100, Math.max(0, ratio * 100));
  const state: Meter["state"] = ratio > 1 ? "over" : ratio >= 1 ? "at_limit" : ratio >= NEAR_LIMIT ? "near" : "ok";
  const tone: Tone = state === "ok" ? "accent" : state === "near" ? "warning" : "danger";
  return { key, used: u, limit, percent, ratio, remaining: Math.max(0, limit - u), state, tone };
}

/** Meters for every quota the plan defines, plus metered-but-uncapped keys the caller asks for. */
export function buildMeters(
  totals: Record<string, number>,
  quotas: Record<string, number>,
  include: string[] = QUOTA_ORDER,
): Meter[] {
  const keys = [
    ...include.filter((k) => k in quotas || k in totals),
    ...Object.keys(quotas).filter((k) => !include.includes(k)),
  ];
  return [...new Set(keys)].map((k) => meterFor(k, totals[k], quotas[k]));
}

/** Metrics that were used but have no quota meter (tokens, storage, …). */
export function otherTotals(totals: Record<string, number>, meterKeys: string[]): Array<[string, number]> {
  return Object.entries(totals)
    .filter(([k]) => !meterKeys.includes(k))
    .sort(([a], [b]) => metricMeta(a).label.localeCompare(metricMeta(b).label));
}

// ------------------------------------------------------------------------------------ daily series
export interface DayPoint {
  date: string; // YYYY-MM-DD (UTC)
  value: number;
}

function isoDay(d: Date): string {
  return d.toISOString().slice(0, 10);
}

/**
 * Daily values for one metric from `by_day` rows ({date, kind, quantity}), filling missing days with
 * zero from the period start through `until` (inclusive, UTC).
 */
export function dailySeries(
  byDay: Array<Record<string, unknown>>,
  kind: string,
  periodStart: string,
  until: Date,
): DayPoint[] {
  const sums = new Map<string, number>();
  for (const row of byDay) {
    if (row.kind !== kind || typeof row.date !== "string") continue;
    const q = typeof row.quantity === "number" ? row.quantity : Number(row.quantity);
    if (!Number.isFinite(q)) continue;
    sums.set(row.date, (sums.get(row.date) ?? 0) + q);
  }
  const start = new Date(`${periodStart}T00:00:00Z`);
  if (Number.isNaN(start.getTime())) return [];
  const end = new Date(Date.UTC(until.getUTCFullYear(), until.getUTCMonth(), until.getUTCDate()));
  const out: DayPoint[] = [];
  for (let d = start; d <= end && out.length < 62; d = new Date(d.getTime() + 86_400_000)) {
    const key = isoDay(d);
    out.push({ date: key, value: sums.get(key) ?? 0 });
  }
  return out;
}

/** Kinds present in `by_day`, most used first. */
export function dailyKinds(byDay: Array<Record<string, unknown>>): string[] {
  const totals = new Map<string, number>();
  for (const row of byDay) {
    if (typeof row.kind !== "string") continue;
    totals.set(row.kind, (totals.get(row.kind) ?? 0) + (Number(row.quantity) || 0));
  }
  return [...totals.entries()].sort((a, b) => b[1] - a[1]).map(([k]) => k);
}

/** A "nice" axis maximum ≥ max (1, 2, 2.5, 5 × 10^n). */
export function niceMax(max: number): number {
  if (!Number.isFinite(max) || max <= 0) return 1;
  const exp = Math.floor(Math.log10(max));
  const base = 10 ** exp;
  for (const m of [1, 2, 2.5, 5, 10]) {
    if (m * base >= max) return m * base;
  }
  return 10 * base;
}
